/*RecursiveTriggerHandler class */
public class RecursiveTriggerHandler{

// static variable which is set to true by default for PlanTrigger.

     public static Boolean isFirstTimePlanTriggerBeforeInsert  = true;
     public static Boolean isFirstTimePlanTriggerAfterInsert = true;
     public static Boolean isFirstTimePlanTriggerBeforeUpdate = true;
     public static Boolean isFirstTimePlanTriggerBeforeDelete = true;
     public static Boolean isFirstTimePlanTriggerAfterDelete = true;
     public static Boolean isFirstTimePlanTriggerAfterUpdate = true;
     
}