/**
 * Test class for the ResetRGUSchedulable
 *
 * @Author Accenture
 * @Date 04/06/15
 */
@isTest
private class ResetTermsAndConditionsAcceptedBatchTest
{
   /* static testmethod void test() {
    //List<user> u = [SELECT Terms_and_Conditions_Accepted__c FROM User Where Terms_and_Conditions_Accepted__c!=null limit 5];
    Test.StartTest();
    Try
    {   
        Profile p = [SELECT Id FROM Profile WHERE Name='Standard User']; 
        User testUser = StoreTestUtility.createUser('storetestuser@comcast.mi.com', p.Id, 'SNU');
        testUser.Terms_and_Conditions_Accepted__c = system.today() - 20;
        insert testUser;
        
        ResetTermsAndConditionsAcceptedBatch Reset =new ResetTermsAndConditionsAcceptedBatch();
        Id BatchId = Database.executeBatch(Reset,600);
    }
    catch(Exception ex){
        
    }
        Test.StopTest();
    }
*/

}