#AddUserDialog {
    width: 400px;
    position: fixed;
    z-index: 10000;
}

#loadingPanel {
    display: block;
    position: relative; width400px;
    height: 200px;
    text-align: center;
    font-family: Arial, Helvetica, sans-serif;
    font-size: 11px;
    color: white;
    background-color: #FFFFFF;
    -moz-opacity: .8;
    opacity: .8;
     filter: alpha(opacity =     80);
}
 